name: Deploy Site
run-name: ${{ github.actor }} just pushed to the development branch
on:
  push:
    # we will only build on push to development branch
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was triggered by ${{ github.event_name }} event."
      - run: echo "The job is running on a ${{ runner.os }} server."
      - run: echo "The name of the branch is ${{ github.ref }} on repo ${{ github.repository }}"

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          name: built-site
          path: dist

      - run: echo "Your directory looks like"
      - run: ls
      - run: echo "Current job status ${{ job.status }}"

  # Deploy job
  deploy:
    # Deployment depends on the build job
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify deployment originates from an appropriate source

    # Deploy the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-actifact@v2
        with:
          name: built-site
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

